#!/usr/bin/env python3
"""DeskOS v2: full-colour AmberELEC 8-bit console icons, retuned light schemes and new dark schemes.

usage: build_deskos_v2.py <DeskOS theme dir (es-theme-deskos)> <AmberELEC 8bit theme dir> <out theme dir> [extras dir]

* Each system window (the "SNES.SYS" desktop window) loses its 1-bit console drawing; the AmberELEC
  console is placed there instead, scaled by a whole number (pixel perfect) and baked at the theme's
  native 640x464 so it shows 1:1 on the R36S. A DeskOS-style checkerboard dither shadow is added to
  the ink layer so it takes the colour scheme like the window shadows do.
* Every palette asset (menus, buttons, switches, no-art card, wallpapers, loading screen) is
  two-colour, so all schemes are generated by exact recolouring of the Classic set.
"""
import os
import re
import shutil
import sys

import numpy as np
from PIL import Image

W, H = 640, 464
CONTENT = (84, 80, 423, 307)            # window content area (x0, y0, x1, y1) inclusive
INFO = (392, 96, 639, 303)              # INFO window (+ shadow) overlapping the content on the right
PLACE = (88, 84, 388, 303)              # where the icon may go (left of the INFO window)
BAND = (26, 319, 613, 428)              # carousel band: keeps a dark fill in dark schemes
MAX_SCALE = 3

# light schemes (retuned so full-colour pixel art sits well) + dark twins
SCHEMES = [
    # name, display, ink, paper
    ("classic", "Classic Cream", "2A2C33", "E9E2C9"),
    ("amber", "Amber", "3A2410", "F2D7A6"),
    ("phosphor", "Green Phosphor", "12301C", "C8EBC6"),
    ("pocket", "Pocket Pea", "26301F", "D2DAAE"),
    ("ice", "Ice Blue", "142038", "D4E4FA"),
    ("bubblegum", "Bubblegum", "35172E", "F4D3E2"),
    ("paperwhite", "Paper White", "1A1A1A", "F4F4F0"),
    ("classic-dark", "Classic Night", "E9E2C9", "24262D"),
    ("amber-dark", "Amber CRT Night", "FFC46B", "21170C"),
    ("phosphor-dark", "Green Phosphor Night", "86F29A", "0C1A11"),
    ("pocket-dark", "Pocket Night", "C9D592", "1C2519"),
    ("ice-dark", "Ice Night", "CFE2FF", "121A28"),
    ("bubblegum-dark", "Bubblegum Night", "FFC9E0", "261624"),
    ("paperwhite-dark", "Midnight", "EDEDE6", "151515"),
]
BASE_INK, BASE_PAPER = "2A2C33", "E9E2C9"

# DeskOS art folder -> icon name in the AmberELEC theme (when different)
ALIAS = {
    "lastplayed": "auto-lastplayed", "favorites": "auto-favorites", "all": "auto-allgames", "neocd": "neogeocd",
    "coleco": "colecovision", "dos": "msdos", "sega32x": "sega32x", "tic80": "tic-80", "pcenginecd": "pce-cd",
    "tg-cd": "tg16cd", "fbneo": "fbn", "pokemini": "pokemini", "retropie": "tools",
}
# AmberELEC images that are not native pixel art (big, resampled) -> keep the DeskOS drawing instead
SKIP = {"custom-collections"}


def hexc(h):
    return tuple(int(h[i:i + 2], 16) for i in (0, 2, 4))


def native(img):
    a = np.asarray(img.convert("RGBA"))
    for k in (8, 6, 5, 4, 3, 2):
        h, w = a.shape[:2]
        if h % k == 0 and w % k == 0:
            b = a[::k, ::k]
            if np.array_equal(np.repeat(np.repeat(b, k, 0), k, 1), a):
                return Image.fromarray(b.copy(), "RGBA")
    return img.convert("RGBA")


def fit_icon(img):
    img = native(img)
    bw, bh = PLACE[2] - PLACE[0] + 1 - 8, PLACE[3] - PLACE[1] + 1 - 8   # room for the shadow
    f = int(min(bw / img.width, bh / img.height))
    if f >= 1:
        f = min(f, MAX_SCALE if max(img.size) > 40 else 8)
        return img.resize((img.width * f, img.height * f), Image.NEAREST)
    s = min(bw / img.width, bh / img.height)                              # oversized, non-native art
    return img.resize((max(1, int(img.width * s)), max(1, int(img.height * s))), Image.BOX)


def amber_icon(amber, folder):
    name = ALIAS.get(folder, folder)
    if name in SKIP or folder in SKIP:
        return None
    t = os.path.join(amber, name, "theme.xml")
    if not os.path.isfile(t):
        return None
    m = re.search(r'name="console_overlay"[^>]*>.*?<path>(.*?)</path>', open(t, errors="ignore").read(), re.S)
    if not m:
        return None
    p = os.path.normpath(os.path.join(amber, name, m.group(1).strip()))
    return Image.open(p) if os.path.isfile(p) else None


def mask(path):
    return np.asarray(Image.open(path).convert("RGBA"))[..., 3] > 127


def save_mask(m, path):
    a = np.zeros((H, W, 4), np.uint8)
    a[..., :3] = 255
    a[..., 3] = m * 255
    Image.fromarray(a, "RGBA").save(path, optimize=True)


def rebuild_system(sysdir, icon):
    ink, pap = mask(os.path.join(sysdir, "screen_ink.png")), mask(os.path.join(sysdir, "screen_paper.png"))
    ys, xs = np.mgrid[0:H, 0:W]
    region = ((xs >= CONTENT[0]) & (xs <= CONTENT[2]) & (ys >= CONTENT[1]) & (ys <= CONTENT[3])
              & ~((xs >= INFO[0]) & (ys >= INFO[1]) & (ys <= INFO[3])))
    ink[region] = False                     # remove the 1-bit console drawing
    pap[region] = True                      # plain window fill
    ic = fit_icon(icon)
    px = PLACE[0] + (PLACE[2] - PLACE[0] + 1 - 4 - ic.width) // 2
    py = PLACE[1] + (PLACE[3] - PLACE[1] + 1 - 4 - ic.height) // 2
    layer = Image.new("RGBA", (W, H), (0, 0, 0, 0))
    layer.alpha_composite(ic, (px, py))
    la = np.asarray(layer)[..., 3] > 127
    # DeskOS dither shadow (ink colour), offset like the window shadows
    sh = np.zeros_like(la)
    sh[4:, 4:] = la[:-4, :-4]
    sh &= ~la & region & (((xs + ys) % 2) == 0)
    ink |= sh
    pap[sh] = False
    # hard-edge the colour layer's alpha (pixel art, no half-transparent fringes)
    a = np.asarray(layer).copy()
    a[..., 3] = np.where(la, 255, 0)
    save_mask(ink, os.path.join(sysdir, "screen_ink.png"))
    save_mask(pap, os.path.join(sysdir, "screen_paper.png"))
    save_cropped(a, os.path.join(sysdir, "screen_icon.png"), (os.path.basename(sysdir), "screen_icon"))


BOXES = {}   # (folder, layer) -> (x, y, w, h) in 640x464 pixels


def save_cropped(a, path, key):
    """Save only the bounding box of an RGBA array; remember where it goes."""
    ys, xs = np.nonzero(a[..., 3])
    x0, x1, y0, y1 = xs.min(), xs.max() + 1, ys.min(), ys.max() + 1
    Image.fromarray(a[y0:y1, x0:x1].copy(), "RGBA").save(path, optimize=True)
    BOXES[key] = (int(x0), int(y0), int(x1 - x0), int(y1 - y0))


def mask_rgba(m):
    a = np.zeros((H, W, 4), np.uint8)
    a[..., :3] = 255
    a[..., 3] = m * 255
    return a


def split_band(sysdir):
    """Move the carousel band out of the window layers into band_ink / band_paper."""
    ink, pap = mask(os.path.join(sysdir, "screen_ink.png")), mask(os.path.join(sysdir, "screen_paper.png"))
    ys, xs = np.mgrid[0:H, 0:W]
    band = (xs >= BAND[0]) & (xs <= BAND[2]) & (ys >= BAND[1]) & (ys <= BAND[3])
    f = os.path.basename(sysdir)
    save_cropped(mask_rgba(ink & band), os.path.join(sysdir, "band_ink.png"), (f, "band_ink"))
    save_cropped(mask_rgba(pap & band), os.path.join(sysdir, "band_paper.png"), (f, "band_paper"))
    save_mask(ink & ~band, os.path.join(sysdir, "screen_ink.png"))
    save_mask(pap & ~band, os.path.join(sysdir, "screen_paper.png"))


def mix(a, b, t):
    a, b = hexc(a), hexc(b)
    return "%02X%02X%02X" % tuple(round(x + (y - x) * t) for x, y in zip(a, b))


def scheme_colors(ink, paper):
    """band ink/paper and wallpaper ink/paper for a scheme."""
    if sum(hexc(paper)) > sum(hexc(ink)):          # light scheme: unchanged DeskOS look
        return ink, paper, ink, paper
    deep = mix(paper, "000000", 0.45)               # dark scheme: dark band + dark wallpaper
    return deep, ink, mix(paper, "000000", 0.55), mix(paper, ink, 0.16)


def recolor(src, dst, ink, paper):
    a = np.asarray(Image.open(src).convert("RGBA")).copy()
    rgb = a[..., :3].astype(int)
    bi, bp = np.array(hexc(BASE_INK)), np.array(hexc(BASE_PAPER))
    is_ink = (np.abs(rgb - bi).sum(-1) < np.abs(rgb - bp).sum(-1))
    a[..., :3] = np.where(is_ink[..., None], np.array(hexc(ink), np.uint8), np.array(hexc(paper), np.uint8))
    out = Image.fromarray(a, "RGBA")
    ext = os.path.splitext(dst)[1].lower()
    if ext == ".png":
        out.save(dst, optimize=True)
    elif ext == ".jpg":
        out.convert("RGB").save(dst, quality=95)
    elif ext == ".gif":
        out.convert("RGB").save(dst)


def insert_after_ink(x, block):
    i = x.index('<image name="sysInk"')
    j = x.index("</image>", i) + len("</image>\n")
    return x[:j] + block + x[j:]


def pos_size(f, layer):
    x, y, w, h = BOXES[(f, layer)]
    return f"<pos>{x / W:.6f} {y / H:.6f}</pos>\n      <size>{w / W:.6f} {h / H:.6f}</size>"


def main():
    src, amber, out = sys.argv[1:4]
    extras = sys.argv[4] if len(sys.argv) > 4 else None
    if os.path.exists(out):
        shutil.rmtree(out)
    shutil.copytree(src, out)

    # 1) system windows
    done, kept = [], []
    sysroot = os.path.join(out, "_art", "systems")
    for folder in sorted(os.listdir(sysroot)):
        d = os.path.join(sysroot, folder)
        if not os.path.isfile(os.path.join(d, "screen_ink.png")):
            continue
        split_band(d)
        icon = amber_icon(amber, folder)
        if icon is None:
            kept.append(folder)
            continue
        rebuild_system(d, icon)
        done.append(folder)

    # per-system theme.xml: add the colour icon layer above the ink layer
    for t in [""] + sorted(os.listdir(out)):          # "" = the root theme.xml (fallback theme)
        p = os.path.join(out, t, "theme.xml")
        if t.startswith("_") or not os.path.isfile(p):
            continue
        rel = "./" if t == "" else "./../"
        x = open(p, encoding="utf-8").read()
        m = re.search(r"_art/systems/([^/]+)/screen_ink\.png", x)
        if not m or "bandInk" in x:
            continue
        f = m.group(1)
        band_el = "".join(
            f'    <image name="{n}" extra="true">\n      {pos_size(f, p)}\n'
            f'      <path>{rel}_art/systems/{f}/{p}.png</path>\n'
            f'      <color>${{{v}}}</color>\n      <zIndex>{z}</zIndex>\n    </image>\n'
            for n, p, v, z in (("bandPaper", "band_paper", "bandPaper", 2), ("bandInk", "band_ink", "bandInk", 3)))
        x = insert_after_ink(x, band_el)
        if f not in done:
            open(p, "w", encoding="utf-8").write(x)
            continue
        icon_el = ('    <image name="sysIcon" extra="true">\n      ' + pos_size(f, "screen_icon") + '\n'
                   f'      <path>{rel}_art/systems/{m.group(1)}/screen_icon.png</path>\n'
                   '      <zIndex>4</zIndex>\n    </image>\n')
        x = x.replace(band_el, band_el + icon_el, 1)
        open(p, "w", encoding="utf-8").write(x)

    # 2) colour schemes: palette art, wallpapers, colorset xml
    pal, wall, cols = (os.path.join(out, "_art", "palette"), os.path.join(out, "_art", "wallpaper"),
                       os.path.join(out, "_inc", "colors"))
    base_pal = os.path.join(src, "_art", "palette", "classic")
    styles = sorted({f.split("_", 1)[1] for f in os.listdir(os.path.join(src, "_art", "wallpaper"))
                     if f.startswith("classic_")})
    template = open(os.path.join(src, "_inc", "colors", "classic.xml"), encoding="utf-8").read()
    for f in os.listdir(cols):
        os.remove(os.path.join(cols, f))
    for d in os.listdir(pal):
        shutil.rmtree(os.path.join(pal, d))
    for f in os.listdir(wall):
        os.remove(os.path.join(wall, f))
    for name, disp, ink, paper in SCHEMES:
        os.makedirs(os.path.join(pal, name))
        for f in os.listdir(base_pal):
            recolor(os.path.join(base_pal, f), os.path.join(pal, name, f), ink, paper)
        band_ink, band_paper, wall_ink, wall_paper = scheme_colors(ink, paper)
        for st in styles:
            recolor(os.path.join(src, "_art", "wallpaper", "classic_" + st), os.path.join(wall, f"{name}_{st}"),
                    wall_ink, wall_paper)
        x = (template.replace("Classic Cream", disp).replace("<palette>classic</palette>", f"<palette>{name}</palette>")
             .replace("/palette/classic/", f"/palette/{name}/").replace(BASE_INK, "@INK@").replace(BASE_PAPER, "@PAPER@")
             .replace("@INK@", ink).replace("@PAPER@", paper))
        x = x.replace("<paperColor>", f"<bandInk>{band_ink}FF</bandInk>\n    <bandPaper>{band_paper}FF</bandPaper>\n"
                      "    <paperColor>", 1)
        sysv = x[x.index('<view name="system">'):x.index("</view>", x.index('<view name="system">'))]
        new = (sysv.replace(f'<image name="logo"><color>{paper}FF', f'<image name="logo"><color>{band_paper}FF')
                   .replace(f'<text name="logoText"><color>{paper}FF', f'<text name="logoText"><color>{band_paper}FF'))
        x = x.replace(sysv, new)
        open(os.path.join(cols, name + ".xml"), "w", encoding="utf-8").write(x)

    # colorset list in main.xml
    mp = os.path.join(out, "_inc", "main.xml")
    x = open(mp, encoding="utf-8").read()
    x = re.sub(r'  <include subset="colorset"[^\n]*\n', "", x)
    entries = "".join(f'  <include subset="colorset" name="{n}" displayName="{d}">./colors/{n}.xml</include>\n'
                      for n, d, _, _ in SCHEMES)
    x = x.replace('  <include subset="fontsize"', entries + '  <include subset="fontsize"', 1)
    open(mp, "w", encoding="utf-8").write(x)

    # optional loading screens (deskos-extras)
    if extras and os.path.isdir(extras):
        base = os.path.join(extras, "loading_classic.png")
        for f in list(os.listdir(extras)):
            if f.startswith("loading_") and not f.startswith("loading_classic."):
                os.remove(os.path.join(extras, f))
        for name, _, ink, paper in SCHEMES:
            for ext in (".png", ".jpg", ".gif"):
                recolor(base, os.path.join(extras, f"loading_{name}{ext}"), ink, paper)

    print(f"icons placed: {len(done)} art folders; kept DeskOS drawing: {' '.join(kept)}")
    print(f"schemes: {len(SCHEMES)}")


if __name__ == "__main__":
    main()
