#!/usr/bin/env python3
"""Generate the NeonGlow theme XML for ArkOS / dArkOS EmulationStation-fcamod (351v).

Screen: 640x480. All coordinates are normalized (0..1).
Tokens inside property values:
  {name}        -> ${name}            (theme variable)
  {accent}      -> ${accent}          (or ${sysColor} in multicolor schemes)
Multicolor schemes re-declare every accent-colored property with ${sysColor}
(defined per system) in an override file parsed after the layouts.
"""
import os
import re
import shutil
import sys
from xml.sax.saxutils import escape

sys.path.insert(0, os.path.dirname(__file__))
from palette import COLORSETS  # noqa: E402
from systems import SYSTEMS  # noqa: E402

TOOLS = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(TOOLS)
THEME = os.path.join(ROOT, "neonglow")
INC = os.path.join(THEME, "_inc")
A = "./../art"  # art path as seen from _inc/*.xml

F_BOLD = f"{A}/fonts/BarlowCondensed-Bold.ttf"
F_SEMI = f"{A}/fonts/BarlowCondensed-SemiBold.ttf"
F_MED = f"{A}/fonts/BarlowCondensed-Medium.ttf"
F_BODY = f"{A}/fonts/Barlow-Medium.ttf"
F_BODY_SEMI = f"{A}/fonts/Barlow-SemiBold.ttf"

GAMELIST_VIEWS = "basic, detailed, video, grid"
ALL_VIEWS = "system, " + GAMELIST_VIEWS

FONT_SIZES = {
    # name: (display, vars)
    "medium": ("MEDIUM", dict(fsList=0.050, lsList=1.42, fsSys=0.070, fsTitle=0.090, fsInfo=0.040,
                              fsHeader=0.052, fsKicker=0.034, fsDesc=0.032, fsMeta=0.036, fsHelp=0.027,
                              fsMenu=0.046, fsMenuTitle=0.064, fsMenuSmall=0.036, fsClock=0.036)),
    "small": ("SMALL", dict(fsList=0.042, lsList=1.45, fsSys=0.060, fsTitle=0.076, fsInfo=0.035,
                            fsHeader=0.045, fsKicker=0.030, fsDesc=0.028, fsMeta=0.032, fsHelp=0.025,
                            fsMenu=0.040, fsMenuTitle=0.056, fsMenuSmall=0.032, fsClock=0.032)),
    "large": ("LARGE", dict(fsList=0.060, lsList=1.36, fsSys=0.080, fsTitle=0.098, fsInfo=0.046,
                            fsHeader=0.058, fsKicker=0.038, fsDesc=0.037, fsMeta=0.040, fsHelp=0.030,
                            fsMenu=0.054, fsMenuTitle=0.072, fsMenuSmall=0.040, fsClock=0.040)),
}

BACKGROUNDS = {
    "dotted": ("DOTTED", f"{A}/bg/dots_full.png"),
    "solid": ("SOLID BLACK / WHITE", f"{A}/bg/none.png"),
    "plus": ("PLUS GRID", f"{A}/bg/plus_full.png"),
}


# --------------------------------------------------------------------------
# tiny XML model
# --------------------------------------------------------------------------
class E:
    def __init__(self, type_, name, extra=False, **props):
        self.type, self.name, self.extra, self.props = type_, name, extra, props

    def xml(self, transform, only_accent=False):
        items = []
        for k, v in self.props.items():
            v = str(v)
            if only_accent and "{accent}" not in v:
                continue
            items.append(f"<{k}>{escape(transform(v))}</{k}>")
        if not items:
            return ""
        extra = ' extra="true"' if self.extra and not only_accent else ""
        return f'    <{self.type} name="{self.name}"{extra}>' + "".join(items) + f"</{self.type}>\n"


class V:
    def __init__(self, names, *elements):
        self.names, self.elements = names, elements

    def xml(self, transform, only_accent=False):
        body = "".join(e.xml(transform, only_accent) for e in self.elements)
        return f'  <view name="{self.names}">\n{body}  </view>\n' if body else ""


def tok(v, accent="${accent}"):
    v = re.sub(r"(?<!\$)\{(\w+)\}", r"${\1}", v)
    return v.replace("${accent}", accent)


def write(path, views=(), variables=None, raw=""):
    out = ['<?xml version="1.0" encoding="UTF-8"?>\n<!-- Generated by tools/build_xml.py -->\n<theme>\n']
    if variables:
        out.append("  <variables>\n")
        for k, v in variables.items():
            out.append(f"    <{k}>{escape(str(v))}</{k}>\n")
        out.append("  </variables>\n")
    out.append(raw)
    for v in views:
        out.append(v.xml(tok))
    out.append("</theme>\n")
    with open(path, "w", encoding="utf-8") as f:
        f.write("".join(out))


def bool_(b):
    return "true" if b else "false"


# --------------------------------------------------------------------------
# shared pieces
# --------------------------------------------------------------------------
def background(glow_pos, glow_size=(1.0, 1.333)):
    return [
        E("image", "bgFill", True, path=f"{A}/bg/pixel.png", pos="0 0", size="1 1", color="{bg}", zIndex=0),
        E("image", "bgPattern", True, path="{bgPattern}", pos="0 0", size="1 1",
          color="{pattern}", zIndex=1),
        E("image", "bgGlow", True, path=f"{A}/bg/radial.png", pos=f"{glow_pos[0]} {glow_pos[1]}",
          origin="0.5 0.5", size=f"{glow_size[0]} {glow_size[1]}", color="{accent}{radial}", zIndex=2),
        E("image", "bgVignette", True, path=f"{A}/bg/vignette.png", pos="0 0", size="1 1",
          color="{vignette}", zIndex=3),
    ]


def helpbar():
    return [
        E("image", "helpBarBg", True, path=f"{A}/bg/pixel.png", pos="0 0.925", size="1 0.075",
          color="{helpBar}", zIndex=35),
        E("image", "helpBarLine", True, path=f"{A}/bg/pixel.png", pos="0 0.925", size="1 0.0025",
          color="{panelEdge}", zIndex=36),
        E("image", "helpBarAccent", True, path=f"{A}/bg/hfade.png", pos="0 0.925", size="0.45 0.0035",
          color="{accent}", zIndex=37),
        E("helpsystem", "help", pos="0.022 0.9625", origin="0 0.5", textColor="{helpText}",
          iconColor="{accent}", fontPath=F_SEMI, fontSize="{fsHelp}"),
    ]


def glow_tile(cx, cy, w, z=20):
    h = w * 640 / 480
    common = dict(pos=f"{cx} {cy}", origin="0.5 0.5", size=f"{w:.4f} {h:.4f}")
    return [
        E("image", "tileBody", True, path=f"{A}/tile/body.png", zIndex=z, **common),
        E("image", "tileGlow", True, path=f"{A}/tile/glow.png", color="{accent}", zIndex=z + 1, **common),
        E("image", "tileLogo", True, path=f"{A}/logos/${{system.theme}}.png", default=f"{A}/logos/_default.png",
          zIndex=z + 2, **common),
    ]


def kicker(text, x=0.04, y=0.028):
    return [
        E("text", "kicker", True, text=text, pos=f"{x} {y}", size="0.5 0.05", fontPath=F_SEMI,
          fontSize="{fsKicker}", color="{dim}", forceUppercase="true", zIndex=30),
        E("image", "kickerBar", True, path=f"{A}/bg/pixel.png", pos=f"{x} {y + 0.052}", size="0.045 0.005",
          color="{accent}", zIndex=30),
    ]


SYSINFO = dict(fontPath=F_SEMI, fontSize="{fsInfo}", color="{accent}", forceUppercase="true",
               backgroundColor="00000000", zIndex=50)


# --------------------------------------------------------------------------
# system view layouts (subset "systemview")
# --------------------------------------------------------------------------
def layout_list():
    return [V("system", *background((0.765, 0.45), (1.05, 1.4)), *kicker("Choose a system"),
              E("carousel", "systemcarousel", type="vertical", pos="0.025 0.095", size="0.575 0.83",
                logoSize="0.41 0.13", logoScale="1.32", maxLogoCount="5", logoAlignment="left",
                color="00000000", zIndex=40, systemInfoDelay="300"),
              E("text", "logoText", fontPath=F_BOLD, fontSize="{fsSys}", color="{text}", forceUppercase="true"),
              E("image", "selMarker", True, path=f"{A}/bg/pixel.png", pos="0.028 0.51", origin="0 0.5",
                size="0.007 0.075", color="{accent}", zIndex=45),
              *glow_tile(0.765, 0.45, 0.44),
              E("text", "systemInfo", pos="0.545 0.775", size="0.44 0.06", alignment="center", **SYSINFO),
              *helpbar())]


def layout_horizontal():
    return [V("system", *background((0.5, 0.42), (1.1, 1.3)), *kicker("Choose a system"),
              E("carousel", "systemcarousel", type="horizontal", pos="0 0.13", size="1 0.54",
                logoSize="0.30 0.40", logoScale="1.32", maxLogoCount="3", color="00000000",
                zIndex=40, systemInfoDelay="300"),
              E("image", "logo", path=f"{A}/icons/${{system.theme}}.png"),
              E("text", "logoText", fontPath=F_BOLD, fontSize="{fsTitle}", color="{text}", forceUppercase="true"),
              E("text", "sysName", True, text="${system.fullName}", pos="0.05 0.675", size="0.9 0.10",
                alignment="center", fontPath=F_BOLD, fontSize="{fsTitle}", color="{text}",
                forceUppercase="true", zIndex=45),
              E("text", "systemInfo", pos="0.05 0.775", size="0.9 0.06", alignment="center", **SYSINFO),
              *helpbar())]


def layout_vertical():
    return [V("system", *background((0.2, 0.5), (0.9, 1.25)),
              E("carousel", "systemcarousel", type="vertical", pos="0.02 0.09", size="0.36 0.835",
                logoSize="0.19 0.2533", logoScale="1.38", maxLogoCount="3", logoAlignment="center",
                color="00000000", zIndex=40, systemInfoDelay="300"),
              E("image", "logo", path=f"{A}/icons/${{system.theme}}.png"),
              E("text", "logoText", fontPath=F_BOLD, fontSize="{fsSys}", color="{text}", forceUppercase="true"),
              *kicker("Choose a system", 0.42, 0.30),
              E("text", "sysName", True, text="${system.fullName}", pos="0.42 0.37", size="0.56 0.37",
                alignment="left", verticalAlignment="top", fontPath=F_BOLD, fontSize="{fsTitle}",
                color="{text}", forceUppercase="true", lineSpacing="1.0", zIndex=45),
              E("text", "systemInfo", pos="0.42 0.745", size="0.56 0.06", alignment="left", **SYSINFO),
              *helpbar())]


def layout_wheel():
    return [V("system", *background((0.78, 0.5), (1.0, 1.333)),
              E("carousel", "systemcarousel", type="vertical_wheel", pos="0.50 0.085", size="0.50 0.84",
                logoSize="0.26 0.3467", logoScale="1.25", maxLogoCount="5", logoAlignment="right",
                logoRotation="24", logoRotationOrigin="-1.25 0.5", color="00000000", zIndex=40,
                systemInfoDelay="300"),
              E("image", "logo", path=f"{A}/icons/${{system.theme}}.png"),
              E("text", "logoText", fontPath=F_BOLD, fontSize="{fsSys}", color="{text}", forceUppercase="true"),
              *kicker("Choose a system", 0.05, 0.30),
              E("text", "sysName", True, text="${system.fullName}", pos="0.05 0.37", size="0.50 0.37",
                alignment="left", verticalAlignment="top", fontPath=F_BOLD, fontSize="{fsTitle}",
                color="{text}", forceUppercase="true", lineSpacing="1.0", zIndex=45),
              E("text", "systemInfo", pos="0.05 0.745", size="0.48 0.06", alignment="left", **SYSINFO),
              *helpbar())]


LAYOUTS = {
    "list": ("VERTICAL LIST + ICON", layout_list),
    "horizontal": ("HORIZONTAL CAROUSEL", layout_horizontal),
    "vertical": ("VERTICAL CAROUSEL", layout_vertical),
    "wheel": ("WHEEL", layout_wheel),
}


# --------------------------------------------------------------------------
# gamelists: left half list, right top 2/3 box art, right bottom 1/3 info
# --------------------------------------------------------------------------
LIST_X, LIST_W = 0.02, 0.47
TOP, BOTTOM = 0.105, 0.91
RX, RW = 0.51, 0.47
SPLIT = TOP + (BOTTOM - TOP) * 2 / 3          # 0.6417
ART = (RX, TOP, RW, SPLIT - TOP - 0.008)        # x, y, w, h
INFO = (RX, SPLIT + 0.008, RW, BOTTOM - SPLIT - 0.008)
ART_C = (RX + RW / 2, TOP + ART[3] / 2)


def panel(name, box, z=15):
    x, y, w, h = box
    return [
        E("ninepatch", name, True, path=f"{A}/ui/panel.png", pos=f"{x} {y:.4f}", size=f"{w} {h:.4f}",
          color="{panel}", zIndex=z),
        E("ninepatch", name + "Edge", True, path=f"{A}/ui/panel_edge.png", pos=f"{x} {y:.4f}",
          size=f"{w} {h:.4f}", color="{panelEdge}", zIndex=z + 1),
    ]


HIDE = ["md_lbl_rating", "md_lbl_releasedate", "md_lbl_developer", "md_lbl_publisher", "md_lbl_genre",
        "md_lbl_players", "md_lbl_lastplayed", "md_lbl_playcount"]
HIDE_VAL = ["md_developer", "md_publisher", "md_players", "md_playcount"]


def gamelist_views():
    header = [
        E("image", "logo", path=f"{A}/icons/${{system.theme}}.png", pos="0.008 0.004", origin="0 0",
          maxSize="0.085 0.1133",
          zIndex=30),
        E("text", "logoText", pos="0.09 0.012", size="0.6 0.075", fontPath=F_BOLD, fontSize="{fsHeader}",
          color="{text}", forceUppercase="true", alignment="left", zIndex=30, visible="false"),
        E("text", "headerName", True, text="${system.fullName}", pos="0.09 0.013", size="0.56 0.07",
          alignment="left", verticalAlignment="center", fontPath=F_BOLD, fontSize="{fsHeader}",
          color="{text}", forceUppercase="true", zIndex=30),
        E("image", "headerBar", True, path=f"{A}/bg/hfade.png", pos="0.09 0.083", size="0.30 0.004",
          color="{accent}", zIndex=30),
    ]
    tl = E("textlist", "gamelist", pos=f"{LIST_X} {TOP}", size=f"{LIST_W} {BOTTOM - TOP:.4f}",
           selectorColor="{accent}", selectorColorEnd="{accent}90", selectorGradientType="horizontal",
           selectedColor="{selText}", primaryColor="{list}", secondaryColor="{accent}", fontPath=F_SEMI,
           fontSize="{fsList}", lineSpacing="{lsList}", alignment="left", horizontalMargin="0.018",
           forceUppercase="false", zIndex=40)
    art_panel = panel("artPanel", ART)
    info_panel = panel("infoPanel", INFO)
    ix, iy, iw, ih = INFO
    pad = 0.02
    info = [
        E("rating", "md_rating", pos=f"{ix + pad} {iy + 0.02:.4f}", size=f"0.17 0.036", color="{accent}",
          unfilledColor="{muted}", filledPath=f"{A}/ui/star_filled.svg", unfilledPath=f"{A}/ui/star_empty.svg",
          zIndex=40),
        E("datetime", "md_releasedate", pos=f"{ix + iw - pad - 0.12:.4f} {iy + 0.012:.4f}", size="0.12 0.05",
          format="%Y", alignment="right", fontPath=F_SEMI, fontSize="{fsMeta}", color="{dim}", zIndex=40),
        E("text", "md_genre", pos=f"{ix + 0.21:.4f} {iy + 0.012:.4f}", size=f"{iw - 0.21 - 0.14 - pad:.4f} 0.05",
          alignment="right", fontPath=F_SEMI, fontSize="{fsMeta}", color="{dim}", forceUppercase="true",
          zIndex=40),
        E("text", "md_description", pos=f"{ix + pad} {iy + 0.072:.4f}", size=f"{iw - 2 * pad:.4f} {ih - 0.09:.4f}",
          fontPath=F_BODY, fontSize="{fsDesc}", color="{desc}", lineSpacing="1.12", alignment="left",
          zIndex=40),
    ]
    art = [
        E("image", "md_image", pos=f"{ART_C[0]:.4f} {ART_C[1]:.4f}", origin="0.5 0.5",
          maxSize=f"{RW - 0.04:.4f} {ART[3] - 0.04:.4f}", default="{noart}", zIndex=30),
    ]
    hidden = [E("text", n, visible="false") for n in HIDE] + \
             [E("text", n, visible="false") for n in HIDE_VAL] + \
             [E("datetime", "md_lastplayed", visible="false"),
              E("text", "md_name", visible="false"),
              E("image", "md_thumbnail", visible="false"),
              E("image", "md_marquee", visible="false")]
    views = [
        V(GAMELIST_VIEWS, *background(ART_C, (0.95, 1.2)), *header, tl, *art_panel, *info_panel, *art, *info,
          *hidden, *helpbar()),
        V("video", E("video", "md_video", pos=f"{ART_C[0]:.4f} {ART_C[1]:.4f}", origin="0.5 0.5",
                     maxSize=f"{RW - 0.04:.4f} {ART[3] - 0.04:.4f}", delay="1.2", showSnapshotNoVideo="true",
                     showSnapshotDelay="true", zIndex=31)),
        # basic view has no metadata: show the system tile and a hint instead
        V("basic", *glow_tile(ART_C[0], ART_C[1] - 0.005, 0.36),
          E("text", "basicTitle", True, text="${system.fullName}", pos=f"{ix + pad} {iy + 0.018:.4f}",
            size=f"{iw - 2 * pad:.4f} 0.06", fontPath=F_BOLD, fontSize="{fsHeader}", color="{text}",
            forceUppercase="true", zIndex=40),
          E("text", "basicHint", True,
            text="Scrape your games to show box art, ratings and descriptions here.",
            pos=f"{ix + pad} {iy + 0.09:.4f}", size=f"{iw - 2 * pad:.4f} {ih - 0.11:.4f}", fontPath=F_BODY,
            fontSize="{fsDesc}", color="{desc}", verticalAlignment="top", lineSpacing="1.12", zIndex=40)),
        V("grid",
          E("imagegrid", "gamegrid", pos=f"{LIST_X} {TOP}", size=f"{LIST_W} {BOTTOM - TOP:.4f}",
            margin="0.012 0.016", autoLayout="3 3", autoLayoutSelectedZoom="1.08", imageSource="image",
            gameImage="{noart}", folderImage="{noart}", scrollDirection="vertical", centerSelection="partial",
            zIndex=40),
          E("gridtile", "default", padding="0.006 0.006", imageColor="FFFFFFFF", backgroundImage=f"{A}/ui/panel.png",
            backgroundCornerSize="0.02 0.02", backgroundColor="{panel}", selectionMode="full"),
          E("gridtile", "selected", backgroundColor="{accent}", imageColor="FFFFFFFF"),
          E("text", "md_name", pos=f"{ix + pad} {iy + 0.06:.4f}", size=f"{iw - 2 * pad:.4f} 0.05",
            fontPath=F_BOLD, fontSize="{fsMeta}", color="{text}", forceUppercase="true", visible="true",
            zIndex=40)),
    ]
    return views


def gridfix():
    # in grid view the description moves down below the game name
    ix, iy, iw, ih = INFO
    pad = 0.02
    return V("grid", E("text", "md_description", pos=f"{ix + pad} {iy + 0.112:.4f}",
                       size=f"{iw - 2 * pad:.4f} {ih - 0.13:.4f}"))


# --------------------------------------------------------------------------
# menu + screen (battery top right, clock)
# --------------------------------------------------------------------------
def menu_views():
    icons = dict(iconBrightnessctl="brightness", iconUI="ui", iconSound="sound", iconGames="games",
                 iconSystem="system", iconScraper="scraper", iconUpdates="updates", iconOptions="options",
                 iconAdvanced="advanced", iconQuit="quit", iconControllers="games", iconNetwork="network",
                 searchIcon="search")
    return [
        V("menu",
          E("menuBackground", "menubg", path=f"{A}/ui/menu.png", color="{menuBg}", centerColor="{menuBg}",
            cornerSize="20 20"),
          E("menuText", "menutitle", fontPath=F_BOLD, fontSize="{fsMenuTitle}", color="{accent}"),
          E("menuText", "menufooter", fontPath=F_SEMI, fontSize="{fsMenuSmall}", color="{dim}"),
          E("menuText", "menutext", fontPath=F_BODY, fontSize="{fsMenu}", color="{text}",
            separatorColor="{menuSep}", selectorColor="{accent}", selectedColor="{selText}"),
          E("menuTextSmall", "menutextsmall", fontPath=F_BODY, fontSize="{fsMenuSmall}", color="{dim}"),
          E("menuSwitch", "menuswitch", pathOn=f"{A}/switch/on_{{accentKey}}.svg",
            pathOff=f"{A}/switch/off_{{off}}.svg"),
          E("menuSlider", "menuslider", path=f"{A}/switch/knob_{{accentKey}}.svg"),
          E("menuButton", "menubutton", path=f"{A}/ui/button.png", filledPath=f"{A}/ui/button_filled.png"),
          E("menuTextEdit", "menutextedit", active=f"{A}/ui/textinput_active.png",
            inactive=f"{A}/ui/textinput.png"),
          E("menuIcons", "menuicons", **{k: f"{A}/menu/{v}.svg" for k, v in icons.items()})),
        V("screen",
          E("batteryIndicator", "batteryIndicator", pos="0.79 0.016", size="0.195 0.048",
            horizontalAlignment="right", itemSpacing="0.006", color="{text}",
            incharge=f"{A}/battery/incharge.svg", full=f"{A}/battery/full.svg", at75=f"{A}/battery/75.svg",
            at50=f"{A}/battery/50.svg", at25=f"{A}/battery/25.svg", empty=f"{A}/battery/empty.svg",
            zIndex=100),
          E("text", "clock", pos="0.60 0.016", size="0.18 0.048", alignment="right", fontPath=F_SEMI,
            fontSize="{fsClock}", color="{dim}")),
    ]


# --------------------------------------------------------------------------
def accent_override(views):
    out = []
    for v in views:
        x = v.xml(lambda s: tok(s, "${sysColor}"), only_accent=True)
        out.append(x)
    return "".join(out)


def main():
    if os.path.isdir(INC):
        shutil.rmtree(INC)
    os.makedirs(INC)

    syscolors = {}
    with open(os.path.join(TOOLS, ".cache", "syscolors.txt")) as f:
        for line in f:
            k, v = line.split()
            syscolors[k] = v

    for cs in COLORSETS:
        v = {k: cs[k] for k in ("bg", "pattern", "radial", "vignette", "text", "list", "dim", "muted", "panel",
                                "panelEdge", "helpBar", "helpText", "selText", "menuBg", "menuSep", "off")}
        v["accent"] = cs["accent"]
        v["accentKey"] = cs["accentKey"]
        v["desc"] = "B9B9C6" if cs["dark"] else "3A3A47"
        v["noart"] = f"{A}/noart/{cs['name']}.png"
        write(os.path.join(INC, f"colors-{cs['name']}.xml"), variables=v)

    for name, (_, fv) in FONT_SIZES.items():
        write(os.path.join(INC, f"font-{name}.xml"), variables=fv)
    for name, (_, path) in BACKGROUNDS.items():
        write(os.path.join(INC, f"bg-{name}.xml"), variables={"bgPattern": path})

    all_views = []
    for name, (_, fn) in LAYOUTS.items():
        views = fn()
        all_views += views
        write(os.path.join(INC, f"layout-{name}.xml"), views)
    gl = gamelist_views() + [gridfix()]
    all_views += gl
    write(os.path.join(INC, "gamelist.xml"), gl)
    mv = menu_views()
    all_views += mv
    write(os.path.join(INC, "menu.xml"), mv)

    # multicolor override: every accent property re-declared with ${sysColor}
    override = accent_override(all_views)
    for cs in COLORSETS:
        if cs["multi"]:
            write(os.path.join(INC, f"multi-{cs['name']}.xml"), raw=override)

    def subset(name, display, items, path_fmt):
        s = [f'  <subset name="{name}" displayName="{display}">\n']
        for key, label in items:
            s.append(f'    <include name="{key}" displayName="{label}">./_inc/{path_fmt.format(key)}</include>\n')
        s.append("  </subset>\n")
        return "".join(s)

    main_xml = ['<?xml version="1.0" encoding="UTF-8"?>\n',
                "<!--\n  NeonGlow - EmulationStation theme for the R36S (ArkOS / dArkOS, 640x480)\n"
                "  Generated by tools/build_xml.py - edit the generator, not this file.\n-->\n",
                "<theme>\n  <formatVersion>6</formatVersion>\n",
                subset("colorset", "COLOR SCHEME", [(c["name"], c["display"]) for c in COLORSETS],
                       "colors-{}.xml"),
                subset("fontsize", "FONT SIZE", [(k, v[0]) for k, v in FONT_SIZES.items()], "font-{}.xml"),
                subset("background", "BACKGROUND STYLE", [(k, v[0]) for k, v in BACKGROUNDS.items()],
                       "bg-{}.xml"),
                "  <include>./_inc/gamelist.xml</include>\n",
                "  <include>./_inc/menu.xml</include>\n",
                subset("systemview", "SYSTEM LIST LAYOUT", [(k, v[0]) for k, v in LAYOUTS.items()],
                       "layout-{}.xml"),
                subset("colorset", "COLOR SCHEME",
                       [(c["name"], c["display"]) for c in COLORSETS if c["multi"]], "multi-{}.xml"),
                "</theme>\n"]
    with open(os.path.join(THEME, "theme.xml"), "w", encoding="utf-8") as f:
        f.write("".join(main_xml))

    # one folder per system: sets the per-system glow color then pulls in the shared theme
    for entry in os.listdir(THEME):
        p = os.path.join(THEME, entry)
        if os.path.isdir(p) and entry not in ("art", "_inc"):
            shutil.rmtree(p)
    for theme in sorted(SYSTEMS):
        d = os.path.join(THEME, theme)
        os.makedirs(d, exist_ok=True)
        with open(os.path.join(d, "theme.xml"), "w", encoding="utf-8") as f:
            f.write('<?xml version="1.0" encoding="UTF-8"?>\n<theme>\n  <formatVersion>6</formatVersion>\n'
                    f"  <variables><sysColor>{syscolors[theme]}</sysColor></variables>\n"
                    "  <include>./../theme.xml</include>\n</theme>\n")
    print(f"xml: {len(SYSTEMS)} system folders, {len(COLORSETS)} color schemes")


if __name__ == "__main__":
    main()
